# Generated by Django 4.1.3 on 2022-12-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sarja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarja', models.CharField(default='', max_length=100)),
                ('vuosi', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['vuosi'],
            },
        ),
        migrations.CreateModel(
            name='Decki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('harvinaisuus', models.IntegerField()),
                ('sarja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sarja')),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
    ]
