# Generated by Django 4.1.3 on 2022-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarja',
            name='vuosi',
            field=models.CharField(default='', max_length=4),
        ),
    ]
