# Generated by Django 4.1.3 on 2022-12-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sarja_vuosi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decki',
            new_name='Pakka',
        ),
        migrations.AlterModelOptions(
            name='sarja',
            options={'ordering': ['nimi']},
        ),
        migrations.RenameField(
            model_name='sarja',
            old_name='sarja',
            new_name='nimi',
        ),
    ]
